[workspace]

members = [
  "1_hello_world",
  "2_primitive_types",
  "3_custom_types",
  "4_variable_bindings",
  "5_types",
  "6_conversion",
  "7_expressions",
  "8_flow_of_control",
  "9_functions",
  "10_modules",
  "11_crates",
  "12_cargo",
  "13_attributes",
  "14_generics",
]
